# Site
name: 'Posts by Ga'
description: 'Writing and Sharing'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/'
disqus: 'demowebsite'
email: 'bryan7.ga@gmail.com'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    bryan:
      name: Bryan Ga
      site: https://bryan.weetizen.com
      avatar: /assets/images/bryan_ga.jpg
      bio: "Hi, I am Bryan, the author of PBG!"
      email: bryan7.ga@gmail.com
      #twitter: https://twitter.com/

    min:
      name:           Minseo Ga
      site:           https://blog.naver.com/belfil
      avatar:         /assets/images/minseo_ga.jpg
      bio:            "Hi, I am Min, the author of PBG!"
      email:          test@test.com
      #twitter:        https://twitter.com/
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Bryan
      avatar: /assets/images/bryan_ga.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
